version: '3.8'

services:
  dahua-proxy:
    image: python:3.11-slim
    container_name: dahua-pushover
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 5005:5000
    command: >
      sh -c "pip install flask requests &&
             python app.py"
    environment:
      - PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - PUSHOVER_USER=${PUSHOVER_USER}
    restart: unless-stopped
networks: {}
